// src/data/countries.js

export const COUNTRIES = [
  { code: "+91", name: "India", countryCode: "IN", pattern: /^[6-9]\d{9}$/, length: 10 },
  { code: "+1", name: "United States", countryCode: "US", pattern: /^\d{10}$/, length: 10 },
  { code: "+1", name: "Canada", countryCode: "CA", pattern: /^\d{10}$/, length: 10 },
  { code: "+44", name: "United Kingdom", countryCode: "GB", pattern: /^\d{10}$/, length: 10 },
  { code: "+61", name: "Australia", countryCode: "AU", pattern: /^\d{9}$/, length: 9 },
  { code: "+81", name: "Japan", countryCode: "JP", pattern: /^\d{10}$/, length: 10 },
  { code: "+86", name: "China", countryCode: "CN", pattern: /^\d{11}$/, length: 11 },
  { code: "+49", name: "Germany", countryCode: "DE", pattern: /^\d{10,11}$/, length: 11 },
  { code: "+33", name: "France", countryCode: "FR", pattern: /^\d{9}$/, length: 9 },
  { code: "+39", name: "Italy", countryCode: "IT", pattern: /^\d{10}$/, length: 10 },
  { code: "+34", name: "Spain", countryCode: "ES", pattern: /^\d{9}$/, length: 9 },
  { code: "+7", name: "Russia", countryCode: "RU", pattern: /^\d{10}$/, length: 10 },
  { code: "+55", name: "Brazil", countryCode: "BR", pattern: /^\d{10,11}$/, length: 11 },
  { code: "+52", name: "Mexico", countryCode: "MX", pattern: /^\d{10}$/, length: 10 },
  { code: "+82", name: "South Korea", countryCode: "KR", pattern: /^\d{9,10}$/, length: 10 },
  { code: "+90", name: "Turkey", countryCode: "TR", pattern: /^\d{10}$/, length: 10 },
  { code: "+971", name: "UAE", countryCode: "AE", pattern: /^\d{9}$/, length: 9 },
  { code: "+966", name: "Saudi Arabia", countryCode: "SA", pattern: /^\d{9}$/, length: 9 },
  { code: "+65", name: "Singapore", countryCode: "SG", pattern: /^\d{8}$/, length: 8 },
  { code: "+60", name: "Malaysia", countryCode: "MY", pattern: /^\d{9,10}$/, length: 10 },
  { code: "+62", name: "Indonesia", countryCode: "ID", pattern: /^\d{10,11}$/, length: 11 },
  { code: "+63", name: "Philippines", countryCode: "PH", pattern: /^\d{10}$/, length: 10 },
  { code: "+66", name: "Thailand", countryCode: "TH", pattern: /^\d{9}$/, length: 9 },
  { code: "+84", name: "Vietnam", countryCode: "VN", pattern: /^\d{9,10}$/, length: 10 },
  { code: "+92", name: "Pakistan", countryCode: "PK", pattern: /^\d{10}$/, length: 10 },
  { code: "+880", name: "Bangladesh", countryCode: "BD", pattern: /^\d{10}$/, length: 10 },
  { code: "+94", name: "Sri Lanka", countryCode: "LK", pattern: /^\d{9}$/, length: 9 },
  { code: "+977", name: "Nepal", countryCode: "NP", pattern: /^\d{10}$/, length: 10 },
  { code: "+27", name: "South Africa", countryCode: "ZA", pattern: /^\d{9}$/, length: 9 },
  { code: "+20", name: "Egypt", countryCode: "EG", pattern: /^\d{10}$/, length: 10 },
  { code: "+234", name: "Nigeria", countryCode: "NG", pattern: /^\d{10}$/, length: 10 },
  { code: "+254", name: "Kenya", countryCode: "KE", pattern: /^\d{9}$/, length: 9 },
  { code: "+31", name: "Netherlands", countryCode: "NL", pattern: /^\d{9}$/, length: 9 },
  { code: "+46", name: "Sweden", countryCode: "SE", pattern: /^\d{9}$/, length: 9 },
  { code: "+47", name: "Norway", countryCode: "NO", pattern: /^\d{8}$/, length: 8 },
  { code: "+45", name: "Denmark", countryCode: "DK", pattern: /^\d{8}$/, length: 8 },
  { code: "+358", name: "Finland", countryCode: "FI", pattern: /^\d{9,10}$/, length: 10 },
  { code: "+48", name: "Poland", countryCode: "PL", pattern: /^\d{9}$/, length: 9 },
  { code: "+380", name: "Ukraine", countryCode: "UA", pattern: /^\d{9}$/, length: 9 },
  { code: "+41", name: "Switzerland", countryCode: "CH", pattern: /^\d{9}$/, length: 9 },
  { code: "+43", name: "Austria", countryCode: "AT", pattern: /^\d{10}$/, length: 10 },
  { code: "+32", name: "Belgium", countryCode: "BE", pattern: /^\d{9}$/, length: 9 },
  { code: "+351", name: "Portugal", countryCode: "PT", pattern: /^\d{9}$/, length: 9 },
  { code: "+353", name: "Ireland", countryCode: "IE", pattern: /^\d{9}$/, length: 9 },
  { code: "+64", name: "New Zealand", countryCode: "NZ", pattern: /^\d{9}$/, length: 9 },
  { code: "+54", name: "Argentina", countryCode: "AR", pattern: /^\d{10}$/, length: 10 },
  { code: "+56", name: "Chile", countryCode: "CL", pattern: /^\d{9}$/, length: 9 },
  { code: "+57", name: "Colombia", countryCode: "CO", pattern: /^\d{10}$/, length: 10 },
  { code: "+51", name: "Peru", countryCode: "PE", pattern: /^\d{9}$/, length: 9 },
  { code: "+972", name: "Israel", countryCode: "IL", pattern: /^\d{9}$/, length: 9 },
  { code: "+974", name: "Qatar", countryCode: "QA", pattern: /^\d{8}$/, length: 8 },
  { code: "+973", name: "Bahrain", countryCode: "BH", pattern: /^\d{8}$/, length: 8 },
  { code: "+968", name: "Oman", countryCode: "OM", pattern: /^\d{8}$/, length: 8 },
  { code: "+965", name: "Kuwait", countryCode: "KW", pattern: /^\d{8}$/, length: 8 },
];