export const postsData = [
  {
    id: 1,
    title: 'VPS Cloud Hosting In India – Fast, Secure & Scalable',
    description: 'Discover how Cloudedata VPS hosting delivers blazing fast speeds, enterprise security with Acronis, and instant scalability for businesses of all sizes.',
    author: 'Arjun Mehta',
    date: '2026-05-18',
    readTime: '5 min read',
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    category: 'Cloud',
    isVideo: false,
  },
  {
    id: 2,
    title: 'Best Tally Cloud Provider in Delhi: Transforming Accounting',
    description: 'Learn how our Tally on Cloud solution helps CA firms and businesses streamline accounting, collaborate in real time, and stay compliant.',
    author: 'Priya Sharma',
    date: '2026-05-15',
    readTime: '7 min read',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80',
    category: 'Tally On Cloud',
    isVideo: true,
    videoDuration: '12:45',
  },
  {
    id: 3,
    title: 'Building a Serverless Data Pipeline on AWS',
    description: 'Step-by-step guide to building a cost-effective serverless data pipeline using Lambda, S3, and Glue for real-time analytics.',
    author: 'Rohan Desai',
    date: '2026-05-10',
    readTime: '6 min read',
    thumbnail: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=800&q=80',
    category: 'Cloud',
    isVideo: true,
    videoDuration: '18:32',
  },
  {
    id: 4,
    title: 'Enterprise-Grade Security with Acronis Backup',
    description: 'How Cloudedata integrates Acronis to protect critical workloads – from ransomware defence to instant recovery and zero data loss.',
    author: 'Simran Kaur',
    date: '2026-05-05',
    readTime: '4 min read',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    category: 'Security',
    isVideo: false,
  },
  {
    id: 5,
    title: 'Migrating to the Cloud: A Complete Checklist',
    description: 'Avoid common pitfalls when moving your business to the cloud. Our checklist covers everything from sizing to security and cost optimisation.',
    author: 'Vikram Singh',
    date: '2026-04-28',
    readTime: '8 min read',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    category: 'Cloud',
    isVideo: false,
  },
  {
    id: 6,
    title: 'How to Scale Your E-commerce Store on Cloud',
    description: 'Practical advice on handling traffic spikes, database scaling, and CDN strategies for high-performing online stores.',
    author: 'Arjun Mehta',
    date: '2026-04-20',
    readTime: '5 min read',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    category: 'Cloud',
    isVideo: true,
    videoDuration: '09:20',
  },
];

export const categoriesData = [
  { name: "Cloud", count: 12 },
  { name: "Tally On Cloud", count: 8 },
  { name: "Security", count: 5 },
  { name: "Infrastructure", count: 7 },
];